### ISSUE TITLE
 syntax error

### ISSUE THREAD

**Issue by emdy** [SzymonLisowiec/php-steamlogin#1]
Parse error: syntax error, unexpected '[', expecting ')' in /home/host/domains/***.com/public_html/escow/example.php on line 5

**Comment by SzymonLisowiec** [comment]
I fixed main.php and example.php to older version of PHP. Check now. ;)

The problem is version of PHP on your server.

**Comment by emdy** [comment]
WORK 59 line is array too ;)
@SzymonLisowiec you even tryd make offer on php-trade-offers and with your php login?

**Comment by SzymonLisowiec** [comment]
Corrected, thanks. :)
Yes, but I don't know how send sentryfile, so you will have 7 days trade ban from this cookies.

Hmmm, Although sentryfile is hashed (sha1) and saved in cookies (cookie name: steamMachineAuthYOUR_STEAMID), but I'm not sure.

**Comment by emdy** [comment]
@SzymonLisowiec you can send full code? i just currecty got out node.js bot because its hard to run node.js console on host
I look up on node bot and mby fix
Check out --> https://github.com/dragonbanshee/node-steam-parentbot

**Comment by SzymonLisowiec** [comment]
I no longer have this code, but this is fast to write:

``` php
<?php
define('php-steamlogin', true);
require('main.php');
$SteamLogin = new SteamLogin(array(
    'username' => '',
    'password' => '',
    'datapath' => dirname(__FILE__) //path to saving cache files
));
if($SteamLogin->success){
    $logindata = $SteamLogin->login();

    require_once 'classes/steam.class.php'; //from: https://github.com/halipso/php-steam-tradeoffers
    $trade = new SteamTrade();
    $trade->setup($logindata->sessionId, $logindata->cookies);

    $options = array(); //https://github.com/halipso/php-steam-tradeoffers#makeofferoptions
    $trade->makeOffer($options);

    if($SteamLogin->error != '') echo $SteamLogin->error;
}else{
    echo $SteamLogin->error;
}
?>
```

**Comment by emdy** [comment]
What i need to update on classes/steam.class.php on line 52? syntax again

**Comment by SzymonLisowiec** [comment]
What returns an error?

**Comment by emdy** [comment]
You have steam?

**Comment by SzymonLisowiec** [comment]
Yes, http://steamcommunity.com/id/pandeu
