### ISSUE TITLE
I don't undestand

### ISSUE THREAD

**Issue by Wolterhon** [SzymonLisowiec/php-steamlogin#10]
Where do I write my twofactor code?

**Comment by SzymonLisowiec** [comment]
```php
$SteamLogin->login(null, $twofactorcode);
```
I repaired syntax of README, now.

**Comment by AndrewRAN** [comment]
Thank you very much, man.

**Comment by Wolterhon** [comment]
Thank you very much, but now I have just an empty page...

**Comment by AndrewRAN** [comment]
Please answer, man

**Comment by Wolterhon** [comment]
I already tried to echo($logindata) and echo($logindata->sessionId) and echo($logindata->cookies)

**Comment by SzymonLisowiec** [comment]
Do you have turn on errors reporting in PHP?

**Comment by Wolterhon** [comment]
Yeah, when echo($logindata) an error told that it's stdClass object and it cannot be converted into a string. But when echo($logindata->sessionId) or ->cookies just an empty page.

**Comment by Wolterhon** [comment]
Man, I made code var_dump and now I get many info, I don't what what part is for cookies.

**Comment by SzymonLisowiec** [comment]
Can you show me your code?

**Comment by Wolterhon** [comment]
`<?php
define('php-steamlogin', true);
require('main.php');

$SteamLogin = new SteamLogin(array(
	'username' => 'cubsonbot',
	'password' => 'pass',
	'datapath' => dirname(__FILE__)
));

if($SteamLogin->success){
	$logindata = $SteamLogin->login(null, '2F8NC');
	var_dump($logindata);
	if($SteamLogin->error != '') echo $SteamLogin->error;
}else{
	echo $SteamLogin->error;
}
?>`

**Comment by SzymonLisowiec** [comment]
Change `dirname(FILE)` on `dirname(__FILE__)`.

**Comment by AndrewRAN** [comment]
Github thought I used markdown...

**Comment by SzymonLisowiec** [comment]
Do you have logindata.json in project catalog after run script? If no, try change chmod of project catalog on 777.
