### ISSUE TITLE
What is "authcode"?

### ISSUE THREAD

**Issue by Govind13100** [SzymonLisowiec/php-steamlogin#11]
I have input the username and password of steam in example.php file.
When i hit the url if shows error

Please enter AUTHCODE available in your e-mail inbox (domain: aohholdings.se).

What is this??

How to get AUTHCODE?????????

**Comment by SzymonLisowiec** [comment]
[https://support.steampowered.com/kb_article.php?ref=4020-ALZM-5519](https://support.steampowered.com/kb_article.php?ref=4020-ALZM-5519)

**Comment by Govind13100** [comment]
okay! thanks for your reply,

What if i got the auth code?
Where to put it?
how to use it??

**Comment by SzymonLisowiec** [comment]
1. Run script
2. You get authcode in your e-mail inbox.
3. Rerun script with `$SteamLogin->login('authcode here')`

**Comment by Govind13100** [comment]
Okay Thanks for your reply :-)

umm one more thing to ask, you have also passed the "$twofactorcode='' is this also mandatory ?????

**Comment by SzymonLisowiec** [comment]
`$twofactorcode` is required, if you have active twofactor authentication on your account (code from mobile app).

**Comment by Govind13100** [comment]
Yeah thank you :-)

I used the authcode in login function and rerun my script , but it is not returning anything, the page is blank and also the json file generated consist only steamid, no sessionid and cookies were there.

**Comment by SzymonLisowiec** [comment]
Show me your script.

**Comment by Govind13100** [comment]
```php
<?php
define('php-steamlogin', true);
require('main.php');

$SteamLogin = new SteamLogin(array(
	'username' => '********',
	'password' => '********'
	'datapath' => dirname(__FILE__) //path to saving cache files
));

if($SteamLogin->success){
	$logindata = $SteamLogin->login('HVNVT');
	/*
	$logindata = array(
		'steamid' => 'xxx', //64-bit
		'sessionId' => 'xxx',
		'cookies' => 'xxx=xxx; yyy=yyy; '
	);
	*/
	
	//You can view steamcommunity.com from created session
	//$SteamLogin->view('http://steamcommunity.com/id/kysune');
	
	//Sending tradeoffers: https://github.com/halipso/php-steam-tradeoffers
	
	if($SteamLogin->error != '') echo $SteamLogin->error;
}else{
	echo $SteamLogin->error;
}
?>
```

I am using the example.php file provided in the package.
thanks in advance!!!

**Comment by SzymonLisowiec** [comment]
```php
<?php
define('php-steamlogin', true);
require('main.php');

$SteamLogin = new SteamLogin(array(
	'username' => '********',
	'password' => '********'
	'datapath' => dirname(__FILE__) //path to saving cache files
));

if($SteamLogin->success){
	
	$logindata = $SteamLogin->login('HVNVT');
	
	if($SteamLogin->error != ''){
		echo $SteamLogin->error;
	}else{
		echo 'Logged successfully!<br />';
		echo 'Your steamid: '.$logindata['steamid'].'<br />';
		echo 'Your sessionId: '.$logindata['sessionId'].'<br />';
		echo 'Your cookies: '.$logindata['cookies'];
	}
	
}else{
	echo $SteamLogin->error;
}
?>
```
Do you need it?

**Comment by Govind13100** [comment]
Yup got all three values. :-)

Thanks for helping :-) :-) :-)
