### ISSUE TITLE
Confused about cookiejar.txt

### ISSUE THREAD

**Issue by AllTerrainAction** [SzymonLisowiec/php-steamlogin#13]
Hi,

I'm trying to get this working; 

I'm getting after $login->success;
Array ( [steamid] => 76561198359392XXX [sessionId] => 5f00b13a8c3bd59923142XXX [cookies] => ) ﻿

My issue is my cookies array/string is returning empty; so I had a poke around and looking at this

`'cookies' => $this->cookiejarToString(file_get_contents($this->config['datapath'].'/cookiejar.txt'))`

Nothing in this script sets /cookiejar.txt with data at any point during login process ? So when the cookiejarToSring function is getting an empty file, am I missing something here?

**Comment by SzymonLisowiec** [comment]
Hello,

Your `datapath` have chmod setted on 777?
