### ISSUE TITLE
We need to publish some files around main.php?

### ISSUE THREAD

**Issue by 777genius** [SzymonLisowiec/php-steamlogin#3]
There's a file can not be found .

**Comment by SzymonLisowiec** [comment]
I don't understand your problem.

**Comment by 777genius** [comment]
What kind of file cookiejar.txt?

**Comment by SzymonLisowiec** [comment]
This is file created by curl.

**Comment by 777genius** [comment]
ErrorException in main.php line 73:
file_get_contents(cookiejar.txt): failed to open stream: No such file or directory

**Comment by 777genius** [comment]
It does not create a file cookiejar.txt

**Comment by 777genius** [comment]
Look my pull request

**Comment by SzymonLisowiec** [comment]
Do you set chmod on 777 for data folder?
Thx for pull request.

**Comment by 777genius** [comment]
The problem was that the file is searched near main.php and not there, where I have to keep.

**Comment by SzymonLisowiec** [comment]
Ok, problem has been fixed.
