### ISSUE TITLE
No cookies.

### ISSUE THREAD

**Issue by GreeMoz** [SzymonLisowiec/php-steamlogin#6]
I get SessionID after login, but cookie is empty.

**Comment by SzymonLisowiec** [comment]
Error when login or steam lag.
30.03.2016 09:35 "Oleg Kornienko" notifications@github.com napisał(a):

**Comment by ghost** [comment]
Same Problem Here. It doesn't even create a cookiejar.txt on it's own. That causes the problem that the main.php can't find the cookiejar.txt: but the problem is that it isn't been created in the fist place. Session and Steam ID are working fine.

**Comment by SzymonLisowiec** [comment]
"datapath" must have chmod = 777
