### ISSUE TITLE
Problems with captcha and authentication

### ISSUE THREAD

**Issue by theochp** [SzymonLisowiec/php-steamlogin#7]
Hi, I'm trying to use this library to connect to my steam account.

First, when I downloaded the library, there was some errors in the classes. I had to fix BigInteger because the MATH_BIGINTEGER_MODE constant wasn't defined.

Also, the variable $enc_password is empty so we can't authenticate.
Event if I try to authenticate without encrypting my password, Steam is asking me a captcha text.

Is the library still working for someone ?

Thanks.

(sorry for my english)

**Comment by SzymonLisowiec** [comment]
Hello,

Can you show your script and give me your php version?
Capatcha displays after many errors when login, one must wait a moment (+/- 0.5h)

I just checked, my script still working.

**Comment by theochp** [comment]
My script is the same as the example:

```
$steamlogin = new SteamLogin([
      'username' => 'tete0148bot',
      'password' => 'myaccountpassword',
      'datapath' => __DIR__ . '/../cache'
    ]);
    if($steamlogin->success) {
        $logindata = $steamlogin->login();
        var_dump($logindata);

        if($steamlogin->error != '')
          echo 'Error: ' . $steamlogin->error;
    } else {
      echo 'Error: ' . $steamlogin->error;
    }
```

When I try this script, the $logindata's content is:
[http://i.imgur.com/VV7JClQ.png](url)

My PHP version is 5.5.12

Thanks.

**Comment by SzymonLisowiec** [comment]
Do you have enabled display_errors and error_reporting?
It is possible that the script does not execute request to steam.

**Comment by theochp** [comment]
It is enabled, no errors.
But as I said, I found something strange. The $enc_password var is empty (empty string) in your SteamLogin class at line 42. I think there is an issue with the encrypting process.
I had to add a constant in the BigInteger file because the MATH_BIGINTEGER_MODE wasn't defined. I set it to 1 which correspond to the MATH_BIGINTEGER_MODE_INTERNAL.

**Comment by SzymonLisowiec** [comment]
Hmmm, Can you check if you work the same function base64_encode and method $rsa->encrypt()?
I tested this script on PHP 5.6.4.

**Comment by theochp** [comment]
I didn't understand. I try an another PHP version ?

**Comment by SzymonLisowiec** [comment]
Yes, You can try with a newer PHP version.

**Comment by theochp** [comment]
Same thing with PHP 5.6

**Comment by SzymonLisowiec** [comment]
Hmmm strange.
You check $rsa object.
And check
$enc_password = $rsa->encrypt($password);
In this incstance, it is empty?

**Comment by theochp** [comment]
When I var_dump $rsa, nothing is printed. And yes $enc_password is an empty string

**Comment by theochp** [comment]
It's working now. I don't know what append. I refreshed the page and it worked.
Sorry for your time. 

Thanks.

**Comment by AndrewRAN** [comment]
xD
