### ISSUE TITLE
can't get cookie "webTradeEligibility"

### ISSUE THREAD

**Issue by NadirRed** [SzymonLisowiec/php-steamlogin#8]
Hello,
Im using your lib to login to steam to get session id and cookies to send trade offer
But i notice that your lib dont get the "webTradeEligibility" cookie
How to fix ?

**Comment by SzymonLisowiec** [comment]
https://www.reddit.com/r/Steam/comments/2r1jw6/how_to_fix_the_market_and_inventory/
